name: Pack extension
on: [push]
jobs:
  pack:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3.3.0
    
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.6.0
        
      - name: Install vsce
        run: npm install --global @vscode/vsce
        
      - name: Pack extension
        run: vsce package
      
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: extension
          path: ./*.vsix
